spring:
  datasource:
    url: jdbc:h2:mem:todomgmtdb
    driverClassName: org.h2.Driver
    username: todouser
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

#Scheduler timer configurations -5Hours default
statusUpdateRule:
  scheduleTimer: 3 # Hours